In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [3]:
#Implement Mean Absolute Error
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [4]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [6]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

mae_np(y_predicted, y_true)

0.5

In [7]:
#Implement Log Loss or Binary Cross Entropy

np.log([0])

epsilon = 1e-15

np.log([1e-15])

C:\Users\aniru\AppData\Local\Temp\ipykernel_20376\3360348160.py:3: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-34.53877639])

In [8]:
y_predicted

array([1, 1, 0, 0, 1])

In [9]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [10]:
1-epsilon

0.999999999999999

In [11]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [12]:
y_predicted_new = np.array(y_predicted_new)

In [13]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [14]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844